/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package cu.edu.cujae.structbd.visual.batter;

import cu.edu.cujae.structbd.dto.batter.ReadBatterDTO;
import cu.edu.cujae.structbd.dto.batter.UpdateBatterDTO;
import cu.edu.cujae.structbd.dto.position.FindPositionDTO;
import cu.edu.cujae.structbd.dto.position.ReadPositionDTO;
import cu.edu.cujae.structbd.dto.team.FindTeamDTO;
import cu.edu.cujae.structbd.dto.team.ReadTeamDTO;
import cu.edu.cujae.structbd.exceptions.team_member.DuplicateMemberNumberException;
import cu.edu.cujae.structbd.exceptions.team_member.EmptyMemberNameException;
import cu.edu.cujae.structbd.services.ServicesLocator;
import cu.edu.cujae.structbd.utils.UtilsConnector;
import java.sql.SQLException;
import java.util.LinkedList;
import java.util.List;

/**
 *
 * @author Hector Angel Gomez
 */
public class UpdateBatterUI extends javax.swing.JDialog {
    private BatterUI parent;
    private ReadBatterDTO batter;
    
    private List<ReadPositionDTO> selectPosition = new LinkedList<>();
    private List<ReadTeamDTO> selectTeams = new LinkedList<>();
    
    public UpdateBatterUI(BatterUI parent, ReadBatterDTO batter) {
        super(parent, true);
        initComponents();
        this.parent = parent;
        this.batter = batter;
        
        this.updateUI();
    }
    
    public void updateUI(){
        try {
            this.teamInput.removeAllItems();
            this.positionInput.removeAllItems();
            
            ReadTeamDTO foundTeam = ServicesLocator.TeamServices.findTeamByID(new FindTeamDTO(this.batter.getTeamID()));
            ReadPositionDTO foundPosition = ServicesLocator.PositionServices.findPosition(new FindPositionDTO(this.batter.getPositionID()));
            
            List<ReadPositionDTO> positions =  ServicesLocator.PositionServices.readBatterPositions();
            List<ReadTeamDTO> teams = ServicesLocator.TeamServices.getTeamsForInsertBatter();
            
            this.selectTeams.clear();
            this.selectTeams.add(foundTeam);
            for(ReadTeamDTO t: teams){
                if(t.getTeam_id() != foundTeam.getTeam_id()){
                    this.selectTeams.add(t);
                }
            }
            
            this.selectPosition.clear();
            this.selectPosition.add(foundPosition);
            for(ReadPositionDTO p: positions){
                if(p.getPositionID() != foundPosition.getPositionID()){
                    this.selectPosition.add(p);
                }
            }
            
            for(ReadPositionDTO p: selectPosition){
                this.positionInput.addItem(p.getPositionName());
            }
            
            for(ReadTeamDTO t: selectTeams){
                this.teamInput.addItem(t.getTeam_name());
            }
            
            this.nameInput.setText(this.batter.getName());
            this.yearnsInTeamInput.setValue(batter.getYearsInTeam());
            this.dorsalInput.setValue(batter.getNumber());
            this.atBatsInput.setValue(batter.getAtBats());
            this.totalHitsInput.setValue(batter.getTotalHits());
        } catch (SQLException | ClassNotFoundException ex) {
            UtilsConnector.viewMessagesUtils.showConecctionErrorMessage(this, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        teamInput = new javax.swing.JComboBox<>();
        nameInput = new javax.swing.JTextField();
        yearnsInTeamInput = new javax.swing.JSpinner();
        dorsalInput = new javax.swing.JSpinner();
        positionInput = new javax.swing.JComboBox<>();
        atBatsInput = new javax.swing.JSpinner();
        totalHitsInput = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificar Bateador");
        setResizable(false);

        jLabel1.setText("Nombre:");

        jButton1.setText("Modificar");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cerrar");
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Equipo:");

        jLabel3.setText("Años en el equipo:");

        jLabel4.setText("Dorsal: ");

        jLabel5.setText("Posición:");

        jLabel6.setText("Veces al Bate:");

        jLabel7.setText("Total de Hits:");

        teamInput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        yearnsInTeamInput.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        dorsalInput.setModel(new javax.swing.SpinnerNumberModel(1, 1, 99, 1));

        positionInput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        atBatsInput.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        totalHitsInput.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(14, 14, 14))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(nameInput))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(teamInput, 0, 188, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(yearnsInTeamInput)
                            .addComponent(dorsalInput)
                            .addComponent(positionInput, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(atBatsInput)
                            .addComponent(totalHitsInput))))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(teamInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(yearnsInTeamInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(dorsalInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(positionInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(atBatsInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(totalHitsInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            int teamIndex = this.teamInput.getSelectedIndex();
            int positionIndex = this.positionInput.getSelectedIndex();
            
            int member_id = this.batter.getMember_id();
            String batterName = this.nameInput.getText();
            int teamID = this.selectTeams.get(teamIndex).getTeam_id();
            int yearsInTeam = (Integer) this.yearnsInTeamInput.getValue();
            int number = (Integer) this.dorsalInput.getValue();
            int positionID = this.selectPosition.get(positionIndex).getPositionID();
            int atBats = (Integer) this.atBatsInput.getValue();
            int totalHits = (Integer) this.totalHitsInput.getValue();
            
            UpdateBatterDTO newBatter = new UpdateBatterDTO(member_id, batterName, teamID, yearsInTeam, number, positionID, atBats, totalHits);
            ServicesLocator.BatterServices.updateBatter(newBatter);
            UtilsConnector.viewMessagesUtils.showSuccessMessage(this, "Bateador actualizado.");
            this.dispose();
            ((BatterUI) this.getParent()).updateUI();
        } catch (EmptyMemberNameException ex) {
            UtilsConnector.viewMessagesUtils.showErrorMessage(this, "El nombre del bateador no puede estar vacío.");
        } catch (SQLException | ClassNotFoundException ex) {
            UtilsConnector.viewMessagesUtils.showConecctionErrorMessage(this, ex);
        } catch (DuplicateMemberNumberException ex) {
            UtilsConnector.viewMessagesUtils.showErrorMessage(this, "Ya existe un miembro del equipo con ese número.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner atBatsInput;
    private javax.swing.JSpinner dorsalInput;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField nameInput;
    private javax.swing.JComboBox<String> positionInput;
    private javax.swing.JComboBox<String> teamInput;
    private javax.swing.JSpinner totalHitsInput;
    private javax.swing.JSpinner yearnsInTeamInput;
    // End of variables declaration//GEN-END:variables
}
