/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package cu.edu.cujae.structbd.visual.game;

import cu.edu.cujae.structbd.dto.game.CreateGameDTO;
import cu.edu.cujae.structbd.services.ServicesLocator;
import java.util.Date;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Amaya
 */
public class CreateGameUI extends javax.swing.JDialog {

    /**
     * Creates new form CreateGameUI
     */
    public CreateGameUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelHomeClub = new javax.swing.JLabel();
        jLabelVisitor = new javax.swing.JLabel();
        jLabelPhase = new javax.swing.JLabel();
        jLabelDate = new javax.swing.JLabel();
        jLabelWinner = new javax.swing.JLabel();
        jLabelAudience = new javax.swing.JLabel();
        jComboBoxHomeClub = new javax.swing.JComboBox<>();
        jComboBoxVisitor = new javax.swing.JComboBox<>();
        jComboBoxPhase = new javax.swing.JComboBox<>();
        jComboBoxWinner = new javax.swing.JComboBox<>();
        jCalendarDate = new com.toedter.calendar.JDateChooser();
        jSpinnerAudience = new javax.swing.JSpinner();
        jButtonClose = new javax.swing.JButton();
        jButtonInsert = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Insertar Juego");

        jLabelHomeClub.setText("Equipo Local:");

        jLabelVisitor.setText("Equipo Visitante:");

        jLabelPhase.setText("Fase:");

        jLabelDate.setText("Fecha:");

        jLabelWinner.setText("Equipo ganador:");

        jLabelAudience.setText("Audiencia:");

        jComboBoxHomeClub.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccionar>" }));
        jComboBoxHomeClub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxHomeClubActionPerformed(evt);
            }
        });

        jComboBoxVisitor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccionar>" }));
        jComboBoxVisitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxVisitorActionPerformed(evt);
            }
        });

        jComboBoxPhase.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccionar>" }));

        jComboBoxWinner.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccionar>" }));
        jComboBoxWinner.setEnabled(false);

        jSpinnerAudience.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jButtonClose.setText("Cerrar");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });

        jButtonInsert.setText("Insertar");
        jButtonInsert.setEnabled(false);
        jButtonInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonInsert)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonClose))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabelHomeClub)
                            .addGap(35, 35, 35)
                            .addComponent(jComboBoxHomeClub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelPhase)
                                    .addComponent(jLabelWinner)
                                    .addComponent(jLabelAudience)
                                    .addComponent(jLabelDate))
                                .addComponent(jLabelVisitor, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jComboBoxPhase, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBoxVisitor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBoxWinner, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jCalendarDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSpinnerAudience, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxHomeClub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelHomeClub))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxVisitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelVisitor))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelWinner)
                    .addComponent(jComboBoxWinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxPhase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPhase))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCalendarDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerAudience, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAudience))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonClose)
                    .addComponent(jButtonInsert))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void jButtonInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertActionPerformed
        // TODO add your handling code here:
        Integer teamHCIndex = jComboBoxHomeClub.getSelectedIndex()-1;
        Integer teamVIndex = jComboBoxVisitor.getSelectedIndex()-1;
        Integer phaseIndex = jComboBoxPhase.getSelectedIndex()-1;
        Integer audience = (Integer)jSpinnerAudience.getValue();
        Date date = jCalendarDate.getDate();
        String winner = jComboBoxWinner.getSelectedItem().toString();
        
        boolean create = true;
        if(teamHCIndex == 0 || teamVIndex == 0 || jComboBoxWinner.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(this, "Debe escoger todos los equipos", "ERROR", JOptionPane.ERROR);
            create = false;
        }
        if(phaseIndex == 0){
            JOptionPane.showMessageDialog(this, "Debe escoger la fase", "ERROR", JOptionPane.ERROR);
            create = false;
        }
        
        if(create){
            //FALTA VALIDAR Y BUSCAR CODIGO DEL EQUIPO Y PONER LOS ERRORES QUE PUEDEN DARSE
            CreateGameDTO createGameDTO = new CreateGameDTO("", "", "", "", date, "", audience);
            this.dispose();
            try {
                ServicesLocator.GameServices.createGame(createGameDTO);
            } catch (SQLException ex) {
                Logger.getLogger(CreateGameUI.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(CreateGameUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButtonInsertActionPerformed

    private void jComboBoxHomeClubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxHomeClubActionPerformed
        // TODO add your handling code here:
        Integer hc = jComboBoxHomeClub.getSelectedIndex();
        Integer v = jComboBoxVisitor.getSelectedIndex();
        if(hc != v && hc != 0 && v != 0){
            jComboBoxWinner.setEnabled(true);
        }
        else{
            jComboBoxWinner.setEnabled(false);
        }
    }//GEN-LAST:event_jComboBoxHomeClubActionPerformed

    private void jComboBoxVisitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxVisitorActionPerformed
        // TODO add your handling code here:
        Integer hc = jComboBoxHomeClub.getSelectedIndex();
        Integer v = jComboBoxVisitor.getSelectedIndex();
        if(hc != v && hc != 0 && v != 0){
            jComboBoxWinner.setEnabled(true);
        }
        else{
            jComboBoxWinner.setEnabled(false);
        }
    }//GEN-LAST:event_jComboBoxVisitorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateGameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateGameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateGameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateGameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CreateGameUI dialog = new CreateGameUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonInsert;
    private com.toedter.calendar.JDateChooser jCalendarDate;
    private javax.swing.JComboBox<String> jComboBoxHomeClub;
    private javax.swing.JComboBox<String> jComboBoxPhase;
    private javax.swing.JComboBox<String> jComboBoxVisitor;
    private javax.swing.JComboBox<String> jComboBoxWinner;
    private javax.swing.JLabel jLabelAudience;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelHomeClub;
    private javax.swing.JLabel jLabelPhase;
    private javax.swing.JLabel jLabelVisitor;
    private javax.swing.JLabel jLabelWinner;
    private javax.swing.JSpinner jSpinnerAudience;
    // End of variables declaration//GEN-END:variables
}
