/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package cu.edu.cujae.structbd.visual.game;

import cu.edu.cujae.structbd.dto.game.CreateGameDTO;
import cu.edu.cujae.structbd.dto.phase.ReadPhaseDTO;
import cu.edu.cujae.structbd.dto.team.ReadTeamDTO;
import cu.edu.cujae.structbd.services.ServicesLocator;
import cu.edu.cujae.structbd.utils.UtilsConnector;
import java.util.Date;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Amaya
 */
public class CreateGameUI extends javax.swing.JDialog {

    /**
     * Creates new form CreateGameUI
     */
    public CreateGameUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        try {
            initComponents();

            //llenar combo box de equipo local
            ArrayList<ReadTeamDTO> teamsListHC = ServicesLocator.TeamServices.readTeams();
            for (int i = 0; i < teamsListHC.size(); i++) {
                jComboBoxHomeClub.addItem(teamsListHC.get(i).getTeam_name());
            }

            //llenar combo box de equipo visitante
            ArrayList<ReadTeamDTO> teamsListVis = ServicesLocator.TeamServices.readTeams();
            for (int i = 0; i < teamsListVis.size(); i++) {
                jComboBoxVisitor.addItem(teamsListVis.get(i).getTeam_name());
            }


        } catch (SQLException ex) {
            Logger.getLogger(CreateGameUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CreateGameUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jLabelHomeClub = new javax.swing.JLabel();
        jComboBoxHomeClub = new javax.swing.JComboBox<>();
        jLabelVisitor = new javax.swing.JLabel();
        jComboBoxVisitor = new javax.swing.JComboBox<>();
        jLabelHomeClub1 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabelVisitor1 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        jLabelDate = new javax.swing.JLabel();
        jCalendarDate = new com.toedter.calendar.JDateChooser();
        jSpinnerAudience = new javax.swing.JSpinner();
        jLabelAudience = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonClose = new javax.swing.JButton();
        jButtonInsert = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Insertar Juego");
        setModal(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelHomeClub.setText("Equipo Local:");

        jComboBoxHomeClub.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccionar>" }));
        jComboBoxHomeClub.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jComboBoxHomeClubActionPerformed(evt);
            }
        });

        jLabelVisitor.setText("Equipo Visitante:");

        jComboBoxVisitor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccionar>" }));
        jComboBoxVisitor.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jComboBoxVisitorActionPerformed(evt);
            }
        });

        jLabelHomeClub1.setText("Carreas equipo local:");

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50, 1));

        jLabelVisitor1.setText("Carreras equipo visitante:");

        jSpinner2.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50, 1));

        jLabelDate.setText("Fecha:");

        jSpinnerAudience.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabelAudience.setText("Audiencia:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelHomeClub1)
                        .addGap(31, 31, 31)
                        .addComponent(jSpinner1)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelHomeClub)
                                .addGap(69, 69, 69)
                                .addComponent(jComboBoxHomeClub, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelVisitor)
                                .addGap(52, 52, 52)
                                .addComponent(jComboBoxVisitor, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelVisitor1)
                                .addGap(8, 8, 8)
                                .addComponent(jSpinner2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelDate)
                                .addGap(106, 106, 106)
                                .addComponent(jCalendarDate, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelAudience)
                                .addGap(84, 84, 84)
                                .addComponent(jSpinnerAudience, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 6, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelHomeClub)
                    .addComponent(jComboBoxHomeClub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelVisitor)
                    .addComponent(jComboBoxVisitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelHomeClub1)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelVisitor1)
                    .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDate)
                    .addComponent(jCalendarDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAudience)
                    .addComponent(jSpinnerAudience, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 300, 180));

        jButtonClose.setText("Cerrar");
        jButtonClose.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonCloseActionPerformed(evt);
            }
        });

        jButtonInsert.setText("Insertar");
        jButtonInsert.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonInsertActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(144, Short.MAX_VALUE)
                .addComponent(jButtonInsert)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonClose)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonClose)
                    .addComponent(jButtonInsert))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 300, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void jButtonInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertActionPerformed
        // TODO add your handling code here:
        Integer audience = (Integer) jSpinnerAudience.getValue();
        Date date = jCalendarDate.getDate();

        try {

            //recuperar id del equipo local
            String teamHC = jComboBoxHomeClub.getSelectedItem().toString();
            ArrayList<ReadTeamDTO> teamsListHC = ServicesLocator.TeamServices.readTeams();
            boolean foundTeamHC = false;
            String teamIdHC = null;
            for (int i = 0; i < teamsListHC.size() && !foundTeamHC; i++) {
                if (teamsListHC.get(i).getTeam_name().equalsIgnoreCase(teamHC)) {
                    foundTeamHC = true;
                    teamIdHC = teamsListHC.get(i).getTeam_id();
                }
            }

            //recuperar id del equipo visitante
            String teamVis = jComboBoxHomeClub.getSelectedItem().toString();
            ArrayList<ReadTeamDTO> teamsListVis = ServicesLocator.TeamServices.readTeams();
            boolean foundTeamV = false;
            String teamIdVis = null;
            for (int i = 0; i < teamsListVis.size() && !foundTeamV; i++) {
                if (teamsListVis.get(i).getTeam_name().equalsIgnoreCase(teamVis)) {
                    foundTeamV = true;
                    teamIdVis = teamsListVis.get(i).getTeam_id();
                }
            }

            //recuperar id del equipo ganador
            String teamW = jComboBoxHomeClub.getSelectedItem().toString();
            ArrayList<ReadTeamDTO> teamsListW = ServicesLocator.TeamServices.readTeams();
            boolean foundTeamW = false;
            String teamIdW = null;
            for (int i = 0; i < teamsListW.size() && !foundTeamW; i++) {
                if (teamsListW.get(i).getTeam_name().equalsIgnoreCase(teamW)) {
                    foundTeamW = true;
                    teamIdW = teamsListW.get(i).getTeam_id();
                }
            }

            //FALTA VALIDAR Y BUSCAR CODIGO DEL EQUIPO Y PONER LOS ERRORES QUE PUEDEN DARSE
            //CreateGameDTO createGameDTO = new CreateGameDTO(gameId, teamIdVis, teamIdVis, phaseId, date, teamIdW, audience);
            //ServicesLocator.GameServices.createGame(createGameDTO);
            this.dispose();
   
        } catch (SQLException ex) {
            Logger.getLogger(CreateGameUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CreateGameUI.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButtonInsertActionPerformed

    private void jComboBoxVisitorActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jComboBoxVisitorActionPerformed
    {//GEN-HEADEREND:event_jComboBoxVisitorActionPerformed

    }//GEN-LAST:event_jComboBoxVisitorActionPerformed

    private void jComboBoxHomeClubActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jComboBoxHomeClubActionPerformed
    {//GEN-HEADEREND:event_jComboBoxHomeClubActionPerformed

    }//GEN-LAST:event_jComboBoxHomeClubActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateGameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateGameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateGameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateGameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CreateGameUI dialog = new CreateGameUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonInsert;
    private com.toedter.calendar.JDateChooser jCalendarDate;
    private javax.swing.JComboBox<String> jComboBoxHomeClub;
    private javax.swing.JComboBox<String> jComboBoxVisitor;
    private javax.swing.JLabel jLabelAudience;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelHomeClub;
    private javax.swing.JLabel jLabelHomeClub1;
    private javax.swing.JLabel jLabelVisitor;
    private javax.swing.JLabel jLabelVisitor1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinnerAudience;
    // End of variables declaration//GEN-END:variables


}
