/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cu.edu.cujae.structbd.visual.game;

import cu.edu.cujae.structbd.dto.game.ReadGameDTO;
import cu.edu.cujae.structbd.services.ServicesLocator;
import cu.edu.cujae.structbd.utils.AppCustomWindow;
import cu.edu.cujae.structbd.utils.RowsRenderer;
import cu.edu.cujae.structbd.visual.snb.SerieUI;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.Iterator;
import java.sql.SQLException;
import java.util.LinkedList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hector Angel Gomez
 */
public class GameUI extends AppCustomWindow {

     private LinkedList<ReadGameDTO> readGameDTO_list;
    
    public void start(){
        initComponents();
        update_list();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableGames = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Juegos");

        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        jTableGames.setAutoCreateRowSorter(true);
        jTableGames.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Fecha", "Equipo Local", "C", "C", "Equipo Visitante", "Fase", "Ganador", "Audiencia"
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableGames);
        if (jTableGames.getColumnModel().getColumnCount() > 0)
        {
            jTableGames.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTableGames.getColumnModel().getColumn(2).setPreferredWidth(30);
            jTableGames.getColumnModel().getColumn(3).setPreferredWidth(30);
            jTableGames.getColumnModel().getColumn(4).setPreferredWidth(100);
            jTableGames.getColumnModel().getColumn(5).setPreferredWidth(50);
            jTableGames.getColumnModel().getColumn(6).setPreferredWidth(100);
            jTableGames.getColumnModel().getColumn(7).setPreferredWidth(40);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    
    public void update_list(){
        try
        {
            DefaultTableModel model = (DefaultTableModel) this.jTableGames.getModel();
            
            int count = model.getRowCount();
            for(int i = 0; i < count; i++){
                model.removeRow(0);
            }
            this.readGameDTO_list = new LinkedList<>(ServicesLocator.GameServices.readAllGames());
            Iterator<ReadGameDTO> it_readGameDTO_list = readGameDTO_list.iterator();
            while (it_readGameDTO_list.hasNext())
            {
                ReadGameDTO readGameDTO = it_readGameDTO_list.next();
                ((DefaultTableModel) jTableGames.getModel()).addRow(new Object[]
                {
                    readGameDTO.getDate().toString(), readGameDTO.getHcTeamName(), readGameDTO.getRuns_home_club(),
                    readGameDTO.getRuns_visitant(), readGameDTO.getVisTeamName(), readGameDTO.getPhaseName(),
                    readGameDTO.getWinner(), readGameDTO.getAudience()
                });
            }
        }
        catch (SQLException | ClassNotFoundException ex)
        {
            Logger.getLogger(GameUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableGames;
    // End of variables declaration//GEN-END:variables
}
