/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package cu.edu.cujae.structbd.visual.game;

import cu.edu.cujae.structbd.dto.game.UpdateGameDTO;
import cu.edu.cujae.structbd.dto.phase.ReadPhaseDTO;
import cu.edu.cujae.structbd.dto.team.ReadTeamDTO;
import cu.edu.cujae.structbd.services.ServicesLocator;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Amaya
 */
public class UpdateGameUI extends javax.swing.JDialog {

    /**
     * Creates new form UpdateGameUi
     */
    public UpdateGameUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        try {
            initComponents();
            
            //llenar combo box de equipo local
            ArrayList<ReadTeamDTO> teamsListHC = ServicesLocator.TeamServices.readTeams();
            for (int i = 0; i < teamsListHC.size(); i++) {
                jComboBoxHomeClub.addItem(teamsListHC.get(i).getTeam_name());
            }
            
            //llenar combo box de equipo visitante
            ArrayList<ReadTeamDTO> teamsListVis = ServicesLocator.TeamServices.readTeams();
            for (int i = 0; i < teamsListVis.size(); i++) {
                jComboBoxVisitor.addItem(teamsListVis.get(i).getTeam_name());
            }
            
            //llenar combo box de fase
            List<ReadPhaseDTO> phaseList = ServicesLocator.PhaseServices.readAllPhase();
            for (int i = 0; i < phaseList.size(); i++) {
                jComboBoxPhase.addItem(phaseList.get(i).getPhase_name());
            }
        } catch (SQLException ex) {
            Logger.getLogger(UpdateGameUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(UpdateGameUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonClose = new javax.swing.JButton();
        jButtonModify = new javax.swing.JButton();
        jSpinnerAudience = new javax.swing.JSpinner();
        jLabelAudience = new javax.swing.JLabel();
        jLabelDate = new javax.swing.JLabel();
        jCalendarDate = new com.toedter.calendar.JDateChooser();
        jComboBoxPhase = new javax.swing.JComboBox<>();
        jLabelPhase = new javax.swing.JLabel();
        jLabelWinner = new javax.swing.JLabel();
        jComboBoxWinner = new javax.swing.JComboBox<>();
        jComboBoxVisitor = new javax.swing.JComboBox<>();
        jLabelVisitor = new javax.swing.JLabel();
        jLabelHomeClub = new javax.swing.JLabel();
        jComboBoxHomeClub = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificar Juego");

        jButtonClose.setText("Cerrar");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });

        jButtonModify.setText("Modificar");
        jButtonModify.setEnabled(false);
        jButtonModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifyActionPerformed(evt);
            }
        });

        jSpinnerAudience.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabelAudience.setText("Audiencia:");

        jLabelDate.setText("Fecha:");

        jComboBoxPhase.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccionar>" }));
        jComboBoxPhase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPhaseActionPerformed(evt);
            }
        });

        jLabelPhase.setText("Fase:");

        jLabelWinner.setText("Equipo ganador:");

        jComboBoxWinner.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccionar>" }));
        jComboBoxWinner.setEnabled(false);

        jComboBoxVisitor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccionar>" }));
        jComboBoxVisitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxVisitorActionPerformed(evt);
            }
        });

        jLabelVisitor.setText("Equipo Visitante:");

        jLabelHomeClub.setText("Equipo Local:");

        jComboBoxHomeClub.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccionar>" }));
        jComboBoxHomeClub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxHomeClubActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonModify)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonClose))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabelHomeClub)
                            .addGap(35, 35, 35)
                            .addComponent(jComboBoxHomeClub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelPhase)
                                    .addComponent(jLabelWinner)
                                    .addComponent(jLabelAudience)
                                    .addComponent(jLabelDate))
                                .addComponent(jLabelVisitor, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jComboBoxPhase, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBoxVisitor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBoxWinner, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jCalendarDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSpinnerAudience, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxHomeClub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelHomeClub))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxVisitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelVisitor))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelWinner)
                    .addComponent(jComboBoxWinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxPhase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPhase))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCalendarDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerAudience, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAudience))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonClose)
                    .addComponent(jButtonModify))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void jButtonModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifyActionPerformed
        // TODO add your handling code here:
        Integer audience = (Integer) jSpinnerAudience.getValue();
        Date date = jCalendarDate.getDate();

        try {
            //recuperar id del equipo local
            String teamHC = jComboBoxHomeClub.getSelectedItem().toString();
            ArrayList<ReadTeamDTO> teamsListHC = ServicesLocator.TeamServices.readTeams();
            boolean foundTeamHC = false;
            String teamIdHC = null;
            for (int i = 0; i < teamsListHC.size() && !foundTeamHC; i++) {
                if (teamsListHC.get(i).getTeam_name().equalsIgnoreCase(teamHC)) {
                    foundTeamHC = true;
                    teamIdHC = teamsListHC.get(i).getTeam_id();
                }
            }

            //recuperar id del equipo visitante
            String teamVis = jComboBoxHomeClub.getSelectedItem().toString();
            ArrayList<ReadTeamDTO> teamsListVis = ServicesLocator.TeamServices.readTeams();
            boolean foundTeamV = false;
            String teamIdVis = null;
            for (int i = 0; i < teamsListVis.size() && !foundTeamV; i++) {
                if (teamsListVis.get(i).getTeam_name().equalsIgnoreCase(teamVis)) {
                    foundTeamV = true;
                    teamIdVis = teamsListVis.get(i).getTeam_id();
                }
            }

            //recuperar id del equipo ganador
            String teamW = jComboBoxHomeClub.getSelectedItem().toString();
            ArrayList<ReadTeamDTO> teamsListW = ServicesLocator.TeamServices.readTeams();
            boolean foundTeamW = false;
            String teamIdW = null;
            for (int i = 0; i < teamsListW.size() && !foundTeamW; i++) {
                if (teamsListW.get(i).getTeam_name().equalsIgnoreCase(teamW)) {
                    foundTeamW = true;
                    teamIdW = teamsListW.get(i).getTeam_id();
                }
            }

            //recuperar codigo de la fase
            String phase = jComboBoxPhase.getSelectedItem().toString();
            List<ReadPhaseDTO> phaseList = ServicesLocator.PhaseServices.readAllPhase();
            boolean foundPhase = false;
            String phaseId = null;
            for (int i = 0; i < phaseList.size() && !foundPhase; i++) {
                if (phaseList.get(i).getPhase_name().equalsIgnoreCase(phase)) {
                    foundPhase = true;
                    phaseId = phaseList.get(i).getPhase_id();
                }
            }
            //FALTA VALIDAR Y BUSCAR CODIGO DEL EQUIPO Y PONER LOS ERRORES QUE PUEDEN DARSE
            UpdateGameDTO updateGameDTO = new UpdateGameDTO("", teamIdVis, teamIdVis, phaseId, date, teamIdW, audience);
            this.dispose();
            ServicesLocator.GameServices.updateGame(updateGameDTO);
        } catch (SQLException ex) {
            Logger.getLogger(CreateGameUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CreateGameUI.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButtonModifyActionPerformed

    private void jComboBoxVisitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxVisitorActionPerformed
        // TODO add your handling code here:
        this.setWinners();
    }//GEN-LAST:event_jComboBoxVisitorActionPerformed

    private void jComboBoxHomeClubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxHomeClubActionPerformed
        // TODO add your handling code here:
        this.setWinners();
    }//GEN-LAST:event_jComboBoxHomeClubActionPerformed

    private void jComboBoxPhaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPhaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPhaseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateGameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateGameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateGameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateGameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UpdateGameUI dialog = new UpdateGameUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonModify;
    private com.toedter.calendar.JDateChooser jCalendarDate;
    private javax.swing.JComboBox<String> jComboBoxHomeClub;
    private javax.swing.JComboBox<String> jComboBoxPhase;
    private javax.swing.JComboBox<String> jComboBoxVisitor;
    private javax.swing.JComboBox<String> jComboBoxWinner;
    private javax.swing.JLabel jLabelAudience;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelHomeClub;
    private javax.swing.JLabel jLabelPhase;
    private javax.swing.JLabel jLabelVisitor;
    private javax.swing.JLabel jLabelWinner;
    private javax.swing.JSpinner jSpinnerAudience;
    // End of variables declaration//GEN-END:variables

    private void setWinners() {
        if (jComboBoxWinner.getItemCount() > 1) {
            jComboBoxWinner.removeAllItems();
            jComboBoxWinner.addItem("<Seleccionar>");
        }
        Integer hc = jComboBoxHomeClub.getSelectedIndex();
        Integer v = jComboBoxVisitor.getSelectedIndex();
        if (hc != v && hc != 0 && v != 0) {
            jComboBoxWinner.setEnabled(true);
            jComboBoxWinner.addItem(jComboBoxHomeClub.getSelectedItem().toString());
            jComboBoxWinner.addItem(jComboBoxVisitor.getSelectedItem().toString());
        } else {
            jComboBoxWinner.setEnabled(false);
        }
    }

}
