/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package cu.edu.cujae.structbd.visual.pitcher;

import cu.edu.cujae.structbd.dto.pitcher.CreatePitcherDTO;
import cu.edu.cujae.structbd.dto.pitcher.UpdatePitcherDTO;
import cu.edu.cujae.structbd.services.ServicesLocator;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Amaya
 */
public class UpdatePitcherUI extends javax.swing.JDialog {
    
    private PitcherUI parentWindow;
    private UpdatePitcherDTO updatePitcherDTO;

    /**
     * Creates new form UpdatePitcherUI
     */
    public UpdatePitcherUI(PitcherUI parent, boolean modal, UpdatePitcherDTO updatePitcherDTO) {
        super(parent, modal);
        initComponents();
        this.parentWindow = parentWindow;
        this.updatePitcherDTO = updatePitcherDTO;
        this.jTextFieldName.setText(updatePitcherDTO.getTeamMemberName());
        //PONER EL EQUIPO CORRESPONDIENTE
        this.jComboBoxTeamName.setSelectedItem(ABORT);
        this.jSpinnerInnings.setValue(updatePitcherDTO.getInningsPitched());
        this.jSpinnerNumber.setValue(updatePitcherDTO.getMemberNumber());
        this.jSpinnerRuns.setValue(updatePitcherDTO.getRunsAllowed());
        this.jSpinnerYearsInTeam.setValue(updatePitcherDTO.getYearsInTeam());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinnerRuns = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabelInnings = new javax.swing.JLabel();
        jSpinnerInnings = new javax.swing.JSpinner();
        jSpinnerYearsInTeam = new javax.swing.JSpinner();
        jLabelYearsInTeam = new javax.swing.JLabel();
        jLabelNumber = new javax.swing.JLabel();
        jSpinnerNumber = new javax.swing.JSpinner();
        jComboBoxTeamName = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButtonModify = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificar Pitcher");

        jSpinnerRuns.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel3.setText("Carreras permitidas:");

        jLabelInnings.setText("Entradas lanzadas:");

        jSpinnerInnings.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jSpinnerYearsInTeam.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabelYearsInTeam.setText("Años en el equipo:");

        jLabelNumber.setText("Número de jugador:");

        jSpinnerNumber.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jComboBoxTeamName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccionar>" }));
        jComboBoxTeamName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTeamNameActionPerformed(evt);
            }
        });

        jLabel1.setText("Equipo:");

        jLabelName.setText("Nombre:");

        jTextFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameActionPerformed(evt);
            }
        });

        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonModify.setText("Modificar");
        jButtonModify.setEnabled(false);
        jButtonModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(jComboBoxTeamName, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabelName)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelNumber)
                                .addComponent(jLabelYearsInTeam)
                                .addComponent(jLabelInnings)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSpinnerNumber)
                                .addComponent(jSpinnerInnings)
                                .addComponent(jSpinnerRuns, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jSpinnerYearsInTeam, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonModify)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelName)
                            .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxTeamName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSpinnerNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNumber))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSpinnerYearsInTeam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelYearsInTeam))
                        .addGap(28, 28, 28))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jSpinnerInnings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelInnings)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerRuns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButtonModify))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameActionPerformed
        // TODO add your handling code here:
        if(jTextFieldName.getText().strip() != "" || jComboBoxTeamName.getSelectedIndex() != 0){
            jButtonModify.setEnabled(true);
        }
        else{
            jButtonModify.setEnabled(false);
        }
    }//GEN-LAST:event_jTextFieldNameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifyActionPerformed
        // TODO add your handling code here:
        String name = jTextFieldName.getText();
        Integer team_index = jComboBoxTeamName.getSelectedIndex()-1;
        String team = jComboBoxTeamName.getSelectedItem().toString();
        Integer yearsInTeam = (Integer) jSpinnerYearsInTeam.getValue();
        Integer number = (Integer) jSpinnerNumber.getValue();
        Integer innings = (Integer) jSpinnerInnings.getValue();
        Integer runs = (Integer) jSpinnerRuns.getValue();
        
        if(name == ""){
            JOptionPane.showMessageDialog(this, "El nombre no puede estar vacío", "ERROR", JOptionPane.ERROR);
        }
        if(jComboBoxTeamName.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(this, "Debe elegir un equipo", "ERROR", JOptionPane.ERROR);
        }
        
        //FALTA VALIDAR Y BUSCAR CODIGO DEL EQUIPO Y PONER LOS ERRORES QUE PUEDEN DARSE
        UpdatePitcherDTO updatePitcherDTO = new UpdatePitcherDTO("", "P", name, number, 
                "", yearsInTeam, innings, runs);
        try {
            ServicesLocator.PitcherServices.updatePitcher(updatePitcherDTO);
        } catch (SQLException ex) {
            Logger.getLogger(UpdatePitcherUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(UpdatePitcherUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_jButtonModifyActionPerformed

    private void jComboBoxTeamNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTeamNameActionPerformed
        // TODO add your handling code here:
        if(jTextFieldName.getText().strip() != "" || jComboBoxTeamName.getSelectedIndex() != 0){
            jButtonModify.setEnabled(true);
        }
        else{
            jButtonModify.setEnabled(false);
        }
    }//GEN-LAST:event_jComboBoxTeamNameActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonModify;
    private javax.swing.JComboBox<String> jComboBoxTeamName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelInnings;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelNumber;
    private javax.swing.JLabel jLabelYearsInTeam;
    private javax.swing.JSpinner jSpinnerInnings;
    private javax.swing.JSpinner jSpinnerNumber;
    private javax.swing.JSpinner jSpinnerRuns;
    private javax.swing.JSpinner jSpinnerYearsInTeam;
    private javax.swing.JTextField jTextFieldName;
    // End of variables declaration//GEN-END:variables
}
