/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package cu.edu.cujae.structbd.visual.pitcher;

import cu.edu.cujae.structbd.dto.pitcher.ReadPitcherDTO;
import cu.edu.cujae.structbd.dto.pitcher.UpdatePitcherDTO;
import cu.edu.cujae.structbd.dto.team.FindTeamDTO;
import cu.edu.cujae.structbd.dto.team.ReadTeamDTO;
import cu.edu.cujae.structbd.exceptions.team_member.EmptyMemberNameException;
import cu.edu.cujae.structbd.exceptions.team_member.DuplicateMemberNumberException;
import cu.edu.cujae.structbd.exceptions.team_member.WrongMemberNumberException;
import cu.edu.cujae.structbd.services.ServicesLocator;
import cu.edu.cujae.structbd.utils.UtilsConnector;
import java.sql.SQLException;
import java.util.LinkedList;
import java.util.List;

/**
 *
 * @author Amaya
 */
public class UpdatePitcherUI extends javax.swing.JDialog {
    private String SELECT_TEAM = "<Seleccione>";
    private PitcherUI parentWindow;
    private ReadPitcherDTO pitcher;
    private LinkedList<ReadTeamDTO> selectTeams = new LinkedList<>();

    /**
     * Creates new form UpdatePitcherUI
     */
    public UpdatePitcherUI(PitcherUI parent, boolean modal, ReadPitcherDTO pitcher) {
        super(parent, modal);
        initComponents();
        this.parentWindow = parent;
        this.pitcher = pitcher;
        
        this.updateUI();
    }
    
    public void updateUI(){
        try {
            this.jComboBoxTeamName.removeAllItems();
            List<ReadTeamDTO> teams = ServicesLocator.TeamServices.getTeamsForInsertPitcher();
            
            ReadTeamDTO foundTeam = ServicesLocator.TeamServices.findTeamByID(new FindTeamDTO(this.pitcher.getTeamID()));
            
            this.selectTeams.clear();
            this.selectTeams.add(foundTeam);
            for(ReadTeamDTO t: teams){
                if(t.getTeam_id() != foundTeam.getTeam_id()){
                    this.selectTeams.add(t);
                }
            }
            
            for(ReadTeamDTO t: this.selectTeams){
                this.jComboBoxTeamName.addItem(t.getTeam_name());
            }
            this.jComboBoxTeamName.setSelectedItem(0);
            
            this.jTextFieldName.setText(pitcher.getTeamMemberName());
            this.jSpinnerInnings.setValue(pitcher.getInningsPitched());
            this.jSpinnerNumber.setValue(pitcher.getMemberNumber());
            this.jSpinnerRuns.setValue(pitcher.getRunsAllowed());
            this.jSpinnerYearsInTeam.setValue(pitcher.getYearsInTeam());
        } catch (SQLException | ClassNotFoundException ex) {
           UtilsConnector.viewMessagesUtils.showConecctionErrorMessage(this, ex);
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinnerRuns = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabelInnings = new javax.swing.JLabel();
        jSpinnerInnings = new javax.swing.JSpinner();
        jSpinnerYearsInTeam = new javax.swing.JSpinner();
        jLabelYearsInTeam = new javax.swing.JLabel();
        jLabelNumber = new javax.swing.JLabel();
        jSpinnerNumber = new javax.swing.JSpinner();
        jComboBoxTeamName = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButtonModify = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificar Pitcher");

        jSpinnerRuns.setModel(new javax.swing.SpinnerNumberModel());

        jLabel3.setText("Carreras permitidas:");

        jLabelInnings.setText("Entradas lanzadas:");

        jSpinnerInnings.setModel(new javax.swing.SpinnerNumberModel());

        jSpinnerYearsInTeam.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabelYearsInTeam.setText("Años en el equipo:");

        jLabelNumber.setText("Número de jugador:");

        jSpinnerNumber.setModel(new javax.swing.SpinnerNumberModel(1, 1, 99, 1));

        jComboBoxTeamName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccionar>" }));
        jComboBoxTeamName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTeamNameActionPerformed(evt);
            }
        });

        jLabel1.setText("Equipo:");

        jLabelName.setText("Nombre:");

        jTextFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameActionPerformed(evt);
            }
        });

        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonModify.setText("Modificar");
        jButtonModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonModify)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelName)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jComboBoxTeamName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jTextFieldName)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelYearsInTeam)
                                    .addComponent(jLabelInnings)
                                    .addComponent(jLabelNumber)
                                    .addComponent(jLabel3))
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSpinnerRuns, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                                    .addComponent(jSpinnerNumber)
                                    .addComponent(jSpinnerYearsInTeam)
                                    .addComponent(jSpinnerInnings))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelName)
                            .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxTeamName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSpinnerNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNumber))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSpinnerYearsInTeam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelYearsInTeam))
                        .addGap(28, 28, 28))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jSpinnerInnings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelInnings)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerRuns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButtonModify))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextFieldNameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifyActionPerformed
        // TODO add your handling code here:
        Integer team_index = jComboBoxTeamName.getSelectedIndex();
        
        int id = this.pitcher.getTeamMemberID();
        String name = jTextFieldName.getText();
        int teamID = this.selectTeams.get(team_index).getTeam_id();
        Integer yearsInTeam = (Integer) jSpinnerYearsInTeam.getValue();
        Integer number = (Integer) jSpinnerNumber.getValue();
        Integer innings = (Integer) jSpinnerInnings.getValue();
        Integer runs = (Integer) jSpinnerRuns.getValue();

        try {
            UpdatePitcherDTO updatePitcherDTO = new UpdatePitcherDTO(id, name,number, teamID, yearsInTeam, innings, runs);
            ServicesLocator.PitcherServices.updatePitcher(updatePitcherDTO);
            UtilsConnector.viewMessagesUtils.showSuccessMessage(this, "Se ha actualizado el pitcher");
            ((PitcherUI) this.getParent()).updateUI();
            this.dispose();
        } catch (SQLException | ClassNotFoundException ex) {
            UtilsConnector.viewMessagesUtils.showConecctionErrorMessage(this, ex);
        } catch (WrongMemberNumberException ex) {
            UtilsConnector.viewMessagesUtils.showErrorMessage(this, ex.getMessage());
        } catch (DuplicateMemberNumberException ex) {
            UtilsConnector.viewMessagesUtils.showErrorMessage(this, "En el equipo ya existe un miembro con ese número");
        } catch (EmptyMemberNameException ex) {
            UtilsConnector.viewMessagesUtils.showErrorMessage(this, "El nombre del pitcher no puede estar vacío");
        }
    }//GEN-LAST:event_jButtonModifyActionPerformed

    private void jComboBoxTeamNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTeamNameActionPerformed
      
    }//GEN-LAST:event_jComboBoxTeamNameActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonModify;
    private javax.swing.JComboBox<String> jComboBoxTeamName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelInnings;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelNumber;
    private javax.swing.JLabel jLabelYearsInTeam;
    private javax.swing.JSpinner jSpinnerInnings;
    private javax.swing.JSpinner jSpinnerNumber;
    private javax.swing.JSpinner jSpinnerRuns;
    private javax.swing.JSpinner jSpinnerYearsInTeam;
    private javax.swing.JTextField jTextFieldName;
    // End of variables declaration//GEN-END:variables
}
