/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package cu.edu.cujae.structbd.visual.phase;

import com.toedter.calendar.JCalendar;
import cu.edu.cujae.structbd.dto.phase.CreatePhaseDTO;
import cu.edu.cujae.structbd.dto.phase.UpdatePhaseDTO;
import cu.edu.cujae.structbd.services.ServicesLocator;
import cu.edu.cujae.structbd.utils.UtilsConnector;
import cu.edu.cujae.structbd.utils.ViewUtils;
import java.sql.SQLException;
import java.time.Instant;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Jose
 */
public class CreatePhase_UI1 extends javax.swing.JDialog
{
    /**
     * Creates new form PhaseUI
     */
    public CreatePhase_UI1(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        field_name = new javax.swing.JTextField();
        spinner_team = new javax.swing.JSpinner();
        date_start = new com.toedter.calendar.JDateChooser();
        date_finish = new com.toedter.calendar.JDateChooser();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Insertar fase");
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });

        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Insertar");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Nombre:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel3.setText("Equipos:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel4.setText("Fecha de inicio:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel5.setText("Fecha de fin:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        field_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                field_nameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                field_nameKeyTyped(evt);
            }
        });
        jPanel2.add(field_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 140, -1));

        spinner_team.setModel(new javax.swing.SpinnerNumberModel(1, 1, 16, 1));
        spinner_team.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                spinner_teamKeyReleased(evt);
            }
        });
        jPanel2.add(spinner_team, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 140, -1));

        date_start.setMaxSelectableDate(new java.util.Date(1735707692000L));
        date_start.setMinSelectableDate(new java.util.Date(1641013292000L));
        date_start.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                date_startKeyReleased(evt);
            }
        });
        jPanel2.add(date_start, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 140, -1));

        date_finish.setMaxSelectableDate(new java.util.Date(1735794092000L));
        date_finish.setMinSelectableDate(new java.util.Date(1672549292000L));
        date_finish.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                date_finishKeyReleased(evt);
            }
        });
        jPanel2.add(date_finish, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 140, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        if (validate_name() && validate_dates()/*&& validate_teams_amount()*/)
        {
        try
        {
            String name = field_name.getText();
            Integer teams = (Integer) spinner_team.getValue();
            Date dStart = date_start.getDate();
            ZoneId defaultZoneId = ZoneId.systemDefault();
            Instant iStart = dStart.toInstant();
            LocalDate start_date = iStart.atZone(defaultZoneId).toLocalDate();
            Date dFinish = date_finish.getDate();
            Instant iFinish = dFinish.toInstant();
            LocalDate finish_date = iFinish.atZone(defaultZoneId).toLocalDate();
            String new_phase_id = UtilsConnector.idUtils.generateUniqueID();
            System.out.println(name);
            CreatePhaseDTO createPhaseDTO = new CreatePhaseDTO(new_phase_id, name, start_date, finish_date, teams);
            ServicesLocator.PhaseServices.createPhase(createPhaseDTO);
            
        }
        catch (SQLException ex)
        {
            Logger.getLogger(CreatePhase_UI1.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (ClassNotFoundException ex)
        {
            Logger.getLogger(CreatePhase_UI1.class.getName()).log(Level.SEVERE, null, ex);
            }
        dispose();
        ((PhaseUI)this.getParent()).updateList();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_formFocusGained
    {//GEN-HEADEREND:event_formFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_formFocusGained

    private void field_nameKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_field_nameKeyReleased
    {//GEN-HEADEREND:event_field_nameKeyReleased
        activate_button();
    }//GEN-LAST:event_field_nameKeyReleased

    private void spinner_teamKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_spinner_teamKeyReleased
    {//GEN-HEADEREND:event_spinner_teamKeyReleased
        activate_button();
    }//GEN-LAST:event_spinner_teamKeyReleased

    private void date_startKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_date_startKeyReleased
    {//GEN-HEADEREND:event_date_startKeyReleased
        activate_button();
    }//GEN-LAST:event_date_startKeyReleased

    private void date_finishKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_date_finishKeyReleased
    {//GEN-HEADEREND:event_date_finishKeyReleased
        activate_button();
    }//GEN-LAST:event_date_finishKeyReleased

    private void field_nameKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_field_nameKeyTyped
    {//GEN-HEADEREND:event_field_nameKeyTyped
        char key = evt.getKeyChar();

        if (!Character.isAlphabetic(key) && !Character.isSpaceChar(key))
        {
            evt.consume();
        }
    }//GEN-LAST:event_field_nameKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(CreatePhase_UI1.class.getName()).log(java.util.logging.Level.SEVERE, null,
                                                                                  ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(CreatePhase_UI1.class.getName()).log(java.util.logging.Level.SEVERE, null,
                                                                                  ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(CreatePhase_UI1.class.getName()).log(java.util.logging.Level.SEVERE, null,
                                                                                  ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(CreatePhase_UI1.class.getName()).log(java.util.logging.Level.SEVERE, null,
                                                                                  ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        /*java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                UpdatePhaseUI dialog = new UpdatePhaseUI(new javax.swing.JFrame());
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        /*java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                UpdatePhaseUI dialog = new UpdatePhaseUI(new javax.swing.JFrame());
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser date_finish;
    private com.toedter.calendar.JDateChooser date_start;
    private javax.swing.JTextField field_name;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner spinner_team;
    // End of variables declaration//GEN-END:variables
    private JCalendar jcalendar1;

    public boolean validate_name()
    {
        boolean result = true;
        boolean flag;
        String nombre = field_name.getText();
        for (int i = 0; i < nombre.length() && result; i++)
        {
            flag = Character.isUpperCase(nombre.charAt(0)) && nombre.charAt(0) != ' ' && (Character.isLetter(nombre.
                                                                                          charAt(i)) || nombre.charAt(i) == ' ');
            if (!flag)
            {
                result = false;
                JOptionPane.showMessageDialog(null, "El nombre de la fase debe iniciar con letra mayúscula", "Nombre incorrecto",
                                              JOptionPane.ERROR_MESSAGE);
            }
        }
        return result;
    }
    
    /*public boolean validate_teams_amount(){
       boolean result = true;
        LinkedList<ReadTeamDTO> read_team_list = new LinkedList<>(ServicesLocator.TeamServices.getAllTeams());
        int amount = (int) this.spinner_team.getValue();
        int teams_amount  = read_team_list.size();
        if (amount > teams_amount){
            result = false;
            JOptionPane.showMessageDialog(null,
                                          "La cantidad de equipos de una fase no puede ser superior a la cantidad de equipos de la serie. La cantidad de equipos de la serie es: " String.valueOf(teams_amount), "Cantidad de equipos incorrecta", JOptionPane.ERROR
        
        );
        }
        return result;
    }*/
    
    public boolean validate_dates(){
        boolean result = true;
        Date dStart = date_start.getDate();
        ZoneId defaultZoneId = ZoneId.systemDefault();
        Instant iStart = dStart.toInstant();
        LocalDate start_date = iStart.atZone(defaultZoneId).toLocalDate();
        Date dFinish = date_finish.getDate();
        Instant iFinish = dFinish.toInstant();
        LocalDate finish_date = iFinish.atZone(defaultZoneId).toLocalDate();
        if (finish_date.isBefore(start_date))
        {
            result = false;
            JOptionPane.showMessageDialog(null, "La fecha de finalización de la fase debe ser posterior a la de inicio",
                                          "Fechas incorrectas", HEIGHT);
        }
        return result;
    }
    
    public void activate_button()
    {
        if (!field_name.getText().isEmpty() && ((int) spinner_team.getValue() > 0))
        {
            jButton2.setEnabled(true);
        }
        else
        {
            jButton2.setEnabled(false);
        }
    }
    
    
    
    
}
